---
{% raw -%}
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  become: True
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Check VM
      command: |
        ignite inspect vm {{ item.instance_id }}
      register: vms
      loop: "{{ lookup('file', molecule_instance_config, errors='ignore') | default([], true) | from_yaml | flatten(levels=1) }}"
      ignore_errors: True

    - name: Destroy molecule instance(s)
      shell: |
        ignite kill "{{ item.item.instance_id }}"
        ignite rm "{{ item.item.instance_id }}"
      register: server
      loop: "{{ vms.results | flatten(levels=1) }}"
      when: item.rc == 0
      async: 7200
      poll: 0

    - name: Wait for instance(s) deletion to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: os_jobs
      until: os_jobs.finished
      when: item.ansible_job_id is defined
      retries: 300
      loop: "{{ server.results | flatten(levels=1) }}"

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
{%- endraw %}
